[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "dist"
  included_files = ["public/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless"
  status = 200

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/serverless"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
